let en = {
  // text
  enter: 'Click To Enter',
  about: 'About Us',
  review: 'Review',
  lamda: 'LAMDA Exams',
  home: 'Home',
  learning_center: 'Learning Center',
  user: 'User Center',
  login: 'Click To Login',
  contact: 'Customer Service',
  share: 'Share To Friends',
  back: "Back",
  name: 'Name',
  chinese_name: "Chinese Name",
  english_name: "English Name",
  certificate_name: "The name that the candidate wants to appear on the certificate",
  certificate_name_clue: "Please type in English or Pinyin, and it should be same as your passport or ID card",
  school: 'School',
  birthday: "Birthday (YY/MM/DD)",
  birthday_clue: "For example: 2020.1.1",
  nationality: "Nationality",
  test_date: "Choose Exam Center",
  test_session: "Choose Exam Session",
  edit: 'Edit Personal Information',
  confirm: 'Confirm',
  choose: "Choose",
  learning_record: 'Learning Record',
  payment_record: 'Payment Record',
  registration: 'Registration',
  registration_grading: "LAMDA Examination Registration",
  language: 'Language',
  gender: 'Choose Gender',
  grade: 'Choose Grade',
  grade_and_class: 'Grade and Class',
  grade_and_class_clue: '1A or 2nd Grade 1st Class',
  phone: 'Phone Number',
  mainland_china: 'Mainland China',
  verification_code: 'Enter Verification Code',
  reset: 'Reset',
  resend_sms: "Resend",
  // window
  login_info1: 'Send Successfully',
  login_info2: 'Please enter a correct phone number',
  login_info3: 'Registration information cannot be empty',
  login_info4: 'Register Successfully',
  login_info5: 'Verification code error',
  login_remind: 'Login First',
  // pay_record
  class_name: 'Name',
  class_price: 'Price',
  pay_time: 'Payment Time',
  order_number: 'Order Number',
  // search_grading_score
  search_grading_title: "Transcript",
  pin_search: "Enter PIN Code...",
  search: "Search",
  error_info: "无查询结果，请检查输入内容是否正确！", 
}

module.exports = {
  content: en
}